### ISSUE TITLE
Requesting Permission to Port to Scala

### ISSUE THREAD

**Issue by driangle** [DelvarWorld/easing-functions#7]
Hi Andrew!

Thanks for creating this simple library. I would like your permission to port this over to Scala. I didn't see a license, so I just want to make sure it's okay with you to pretty much copy the code and re-implement it in Scala. I will attribute the original source to you and link to this repo and your demo page as a reference.

Thanks!

**Comment by Sphinxxxx** [comment]
According to [package.json](https://github.com/AndrewRayCode/easing-utils/blob/master/package.json#L23), it's the MIT license.
